return {
  grunt = {cost = 1, speed = 1, health = 1, damage = 1, img = love.graphics.newImage("grunt.png")},
  fighter = {cost = 2, speed = 1.3, health = 2, damage = 1, img = love.graphics.newImage("fighter.png")},
  jogger = {cost = 2, speed = 1.5, health = 1, damage = 1, img = love.graphics.newImage("jogger.png")},
  soldier = {cost = 3, speed = 2, health = 3, damage = 2, img = love.graphics.newImage("soldier.png")},
  lightweight = {cost = 3, speed = 1.4, health = 6, damage = 1, img = love.graphics.newImage("lightweight.png")},
  spark = {cost = 3, speed = 1.7, health = 2, damage = 3, img = love.graphics.newImage("spark.png")},
  elite = {cost = 4, speed = 1.8, health = 3, damage = 2, img = love.graphics.newImage("elite.png")},
  runner = {cost = 4, speed = 2.5, health = 2, damage = 1, img = love.graphics.newImage("runner.png")},
  middleweight = {cost = 5, speed = 1.7, health = 8, damage = 2, img = love.graphics.newImage("middleweight.png")},
  captain = {cost = 5, speed = 2.2, health = 4, damage = 3, img = love.graphics.newImage("captain.png")},
  flame = {cost = 5, speed = 2.4, health = 3, damage = 5, img = love.graphics.newImage("flame.png")},
  general = {cost = 6, speed = 2.5, health = 5, damage = 3, img = love.graphics.newImage("general.png")},
  sprinter = {cost = 6, speed = 3.2, health = 3, damage = 2, img = love.graphics.newImage("sprinter.png")},
  heavyweight = {cost = 7, speed = 2, health = 12, damage = 3, img = love.graphics.newImage("heavyweight.png")},
  inferno = {cost = 7, speed = 3, health = 4, damage = 8, img = love.graphics.newImage("inferno.png")},
}
