return {
  grunt = {cost = 1, speed = 1, health = 1, w = 4, h = 4},
  jogger = {cost = 2, speed = 2, health = 1, w = 4, h = 4},
  wide = {cost = 2, speed = 1, health = 2, w = 6, h = 6},
  beef = {cost = 3, speed = 1.5, health = 3, w = 6, h = 6},
  dasher = {cost = 3, speed = 3, health = 1, w = 4, h = 4},
  elite = {cost = 3, speed = 2, health = 2, w = 6, h = 6},
  heavy = {cost = 4, speed = 1.6, health = 5, w = 8, h = 8},
  sprinter = {cost = 6, speed = 4, health = 2, w = 6, h = 6},
  chungus = {cost = 6, speed = 1.8, health = 7, w = 8, h = 8},
  brawler = {cost = 7, speed = 2.5, health = 4, w = 6, h = 6},
  torchbearer = {cost = 8, speed = 6, health = 5, w = 6, h = 6},
  shield = {cost = 9, speed = 2, health = 10, w = 10, h = 10},
  captain = {cost = 10, speed = 3.8, health = 8, w = 8, h = 8},
}
