return {
  mk1 = {score = 1, range = 1.2, damage = 1, cooldown = 1, behavior = 1, img = love.graphics.newImage("mk1.png"), guns = {{x = 30, y = 16}}},
  mk2 = {score = 2, range = 1.6, damage = 1, cooldown = .95, behavior = 1, img = love.graphics.newImage("mk2.png"), guns = {{x = 31, y = 16}}},
  double = {score = 2, range = 1.4, damage = 1, cooldown = .8, behavior = 1, img = love.graphics.newImage("double.png"), guns = {{x = 30, y = 13}, {x = 30, y = 19}}},
  baron = {score = 2, range = 1.3, damage = 2, cooldown = 1, behavior = 3, img = love.graphics.newImage("baron.png"), guns = {{x = 30, y = 16}}},
  hawk = {score = 3, range = 1.8, damage = 1, cooldown = 1, behavior = 2, img = love.graphics.newImage("hawk.png"), guns = {{x = 32, y = 16}}},
  mk3 = {score = 3, range = 2, damage = 1, cooldown = .9, behavior = 1, img = love.graphics.newImage("mk3.png"), guns = {{x = 32, y = 16}}},
  earl = {score = 4, range = 1.7, damage = 3, cooldown = 1, behavior = 3, img = love.graphics.newImage("earl.png"), guns = {{x = 30, y = 16}}},
  mk4 = {score = 4, range = 2.1, damage = 2, cooldown = .85, behavior = 1, img = love.graphics.newImage("mk4.png"), guns = {{x = 32, y = 16}}},
  triple = {score = 5, range = 1.7, damage = 1, cooldown = .65, behavior = 1, img = love.graphics.newImage("triple.png"), guns = {{x = 30, y = 11}, {x = 30, y = 16}, {x = 30, y = 21}}},
  falcon = {score = 5, range = 2.4, damage = 2, cooldown = .9, behavior = 2, img = love.graphics.newImage("falcon.png"), guns = {{x = 32, y = 16}}},
  mk5 = {score = 6, range = 2.2, damage = 2, cooldown = .8, behavior = 1, img = love.graphics.newImage("mk5.png"), guns = {{x = 32, y = 16}}},
  duke = {score = 6, range = 2, damage = 4, cooldown = 1, behavior = 3, img = love.graphics.newImage("earl.png"), guns = {{x = 32, y = 16}}},
  quad = {score = 6, range = 2.2, damage = 1, cooldown = .5, behavior = 1, img = love.graphics.newImage("quad.png"), guns = {{x = 30, y = 10}, {x = 30, y = 13}, {x = 30, y = 19}, {x = 30, y = 22}}},
  eagle = {score = 6, range = 2.5, damage = 2, cooldown = .85, behavior = 2, img = love.graphics.newImage("eagle.png"), guns = {{x = 32, y = 16}}},
}
